### ISSUE TITLE
Safari Bug

### ISSUE THREAD

**Issue by ebellempire** [omeka/plugin-ItemOrder#8]
Using Safari (15.5, macOS Monterey), items disappear when dragging into order. Refreshing the page restores them to the correct drop position. Should be easy to reproduce but let me know if you need more details.

**Comment by sharonmleon** [comment]
Thanks for filing this, Erin. I'm having trouble reproducing it, but I found something else that's off.

**Comment by zerocrates** [comment]
Looks like we've had a couple unsuccessful attempts at reproducing this specific issue. Any more details to share or it's just an "always happens" kind of thing for you?

**Comment by ebellempire** [comment]
Yeah, it's odd; no error is logged and I don't see any changes in the styles using Safari's web inspector. Nonetheless, it looks like the list elements are losing their height values and the width value, which is usually 100% of the available space, is also dropping down to something like the intrinsic width of the inner content. 

Changing the viewport width resets everything to normal. 

Adding `position: relative` to `#sortable li` seems to prevent this altogether, although there would probably be a few other things that need to change higher up to prevent the list from flowing over the end of the container.

# Installation details
The site is running on Omeka 3.0. Below is the list of active plugins. 

Active Plugins | Version
-- | --
AdminImages | 1.4
Commenting | 2.4
HideElements | 1.3
ItemOrder | 2.0.2
OaiPmhRepository | 2.2
SearchByMetadata | 1.2.1
SimplePages | 3.2.1
SimpleVocab | 2.2.3

# Screen capures
<img width="1422" alt="Screen Shot 2022-06-15 at 4 48 16 PM" src="https://user-images.githubusercontent.com/441279/173926017-0f7fd41f-7bf8-4bc5-b99e-4b4837915999.png">

[screen capture video](https://user-images.githubusercontent.com/441279/173925905-0f840762-998e-4f7e-8aaf-ead2abb40dee.mov)

**Comment by zerocrates** [comment]
Thanks for the detailed information.

There's something a little odd about how your Item Order looks, the styling of the sortable boxes, the numbers, the listing of media for each item... is it possible that this is a modified version or a fork that you're using?

**Comment by ebellempire** [comment]
Ok, I just compared in Git and, while they had the same version number (etc), my version has been actually modified in many strange and seemingly pointless ways. I'm so sorry you spent time on this. 🤦‍♂️

**Comment by zerocrates** [comment]
It's no problem.

We'll probably end up making some improvements here anyway, as the styling has become pretty rough on 3.0 especially.
